/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: DaedalusFinal2.html
Story format: Sugar
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Sugar;

public partial class @DaedalusFinal2: Cradle.StoryFormats.Sugar.SugarStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------


	@DaedalusFinal2()
	{
		this.StartPassage = "Home";

		base.Vars = new VarDefs() { Story = this, StrictMode = false };


		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
		passage11_Init();
		passage12_Init();
		passage13_Init();
		passage14_Init();
		passage15_Init();
		passage16_Init();
		passage17_Init();
		passage18_Init();
		passage19_Init();
		passage20_Init();
		passage21_Init();
		passage22_Init();
		passage23_Init();
		passage24_Init();
		passage25_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Home

	void passage1_Init()
	{
		this.Passages[@"Home"] = new StoryPassage(@"Home", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text(@"This corner of the labyrinth is the safest place you could find to keep you and your son sheltered. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"It is the only part of the maze that opens up to the outside world. A sheer cliff face drops off and below, you can hear the ocean waves crash against unforgiving stone. Birds freewheel through the sea breeze, mocking you in their flight. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"For years you and your son have been trapped here, scavenging what you could from within these walls to survive. For years your mind has been fixated on the thought of freeom, of inventing a way out of this place. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"Today is the day. Your invention is almost ready. You'll soon be rid of this place forever. You just need to take one last journey into the maze, collecting feathers for what will be your last invention. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"Onwards", @"Onwards", null);
		yield return lineBreak();
		yield return lineBreak();
		yield break;
	}


	// .............
	// #2: Onwards

	void passage2_Init()
	{
		this.Passages[@"Onwards"] = new StoryPassage(@"Onwards", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text(@"Double-click this passage to edit it.");
		yield return lineBreak();
		yield break;
	}


	// .............
	// #3: Feather 1

	void passage3_Init()
	{
		this.Passages[@"Feather 1"] = new StoryPassage(@"Feather 1", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text(@"This is like no ordinary maze. There is no way in and there is no way out. Those consigned to walk its walls will do so for all of eternity.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"--");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"You find a feather here, nestled in the crack between two stones.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"Onwards", @"Onwards", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield break;
	}


	// .............
	// #4: Feather 2

	void passage4_Init()
	{
		this.Passages[@"Feather 2"] = new StoryPassage(@"Feather 2", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text(@"You try to think of what Icarus must be going through, living every moment of his life with only fear and silence. What little does he remember of the outside world?");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"--");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"A feather, damp but usable, clings to one of the loose stones here. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"Onwards", @"Onwards", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #5: Feather 3

	void passage5_Init()
	{
		this.Passages[@"Feather 3"] = new StoryPassage(@"Feather 3", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text(@"How did you end up in this place? You try to trace back the chain of events, but every thread seems tangled, every piece disjointed. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"The real madness, you think, was building this maze in the first place. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"--");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"A feather drifts down from above your head. You snatch it from the air. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"Onwards", @"Onwards", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #6: Feather 4

	void passage6_Init()
	{
		this.Passages[@"Feather 4"] = new StoryPassage(@"Feather 4", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text(@"Has it been months? Years? You have had little to reference but the length of your hair and the hollow of your stomach. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"Little Icarus had tried to keep track at first. But as days drifted into weeks, he began to slump under the futility of such a task.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"--");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"A feather, pristine, lies on the floor before you. You carefully tuck it away. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"Onwards", @"Onwards", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #7: Feather 5

	void passage7_Init()
	{
		this.Passages[@"Feather 5"] = new StoryPassage(@"Feather 5", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text(@"You feel the halting of your breath, the way each gasp catches in your throat. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"A thought tries to work its way to conscious in your mind, something you try to bury back inside of you. The fear that even escaping from this maze will not mean freedom. The longing for that other means of release.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"--");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"A feather sits here in the grime. You take it and hurry on. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"Onwards", @"Onwards", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield break;
	}


	// .............
	// #8: Feather 6

	void passage8_Init()
	{
		this.Passages[@"Feather 6"] = new StoryPassage(@"Feather 6", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text(@"You used to think yourself a genius, that your mind could provide you with whatever you desired. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"Now, your desires are few. A warm bed. The ability to laugh with your child.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"--");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"You find a feather here, in the cracks between two stones. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"Onwards", @"Onwards", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #9: Feather 10

	void passage9_Init()
	{
		this.Passages[@"Feather 10"] = new StoryPassage(@"Feather 10", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		yield return text(@"A small stone box, unadorned, sits here, a question engraved into its top. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"Three buttons decorate its sides. You reason that pressing one of the buttons will open the box. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"The lid reads, ''Why do you want freedom?''");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"Press ""I want to live without every moment marked by fear"" ", @"answer2", null);
		yield return lineBreak();
		yield return link(@"Press ""I want revenge for what has been done to me"" ", @"answer2", null);
		yield return lineBreak();
		yield return link(@"Press ""I want my son to know the world beyond these walls"" ", @"answer2", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #10: Feather 9

	void passage10_Init()
	{
		this.Passages[@"Feather 9"] = new StoryPassage(@"Feather 9", new string[]{  }, passage10_Main);
	}

	IStoryThread passage10_Main()
	{
		yield return text(@"A small stone box sits here, shining under the light of your lantern. You can see that its lid is marked with a question. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"Three buttons decorate its sides. You reason that pressing one of the buttons will open the box. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"The lid reads, ''What keeps you here?''");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"Press ""My own inability keeps me here. If only I could think of a means of escape..."" ", @"answer1", null);
		yield return lineBreak();
		yield return link(@"Press ""A tyrant-king keeps me here, to be locked away forever"" ", @"answer1", null);
		yield return lineBreak();
		yield return link(@"Press ""You keep me here by denying me what I need"" ", @"answer1", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #11: Feather 8

	void passage11_Init()
	{
		this.Passages[@"Feather 8"] = new StoryPassage(@"Feather 8", new string[]{  }, passage11_Main);
	}

	IStoryThread passage11_Main()
	{
		yield return text(@"A small stone box, its corners crumbling, sits here. A question is engraved into its lid. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"Three buttons decorate its sides. You reason that pressing one of the buttons will open the box. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"The lid reads, ''Why are you here?''");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"Press ""I was trapped here by my own hubris""", @"answer1", null);
		yield return lineBreak();
		yield return link(@"Press ""I was imprisoned here by a cruel tyrant""", @"answer1", null);
		yield return lineBreak();
		yield return link(@"Press ""I am not here. Walls cannot hold my mind""", @"answer1", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #12: Feather 7

	void passage12_Init()
	{
		this.Passages[@"Feather 7"] = new StoryPassage(@"Feather 7", new string[]{  }, passage12_Main);
	}

	IStoryThread passage12_Main()
	{
		yield return text(@"A small stone box covered with lichen sits here, a question engraved into its top. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"Three buttons decorate its sides. You reason that pressing one of the buttons will open the box. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"The lid reads, ''Who are you?''");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"Press ""I am Daedalus, inventor and father""", @"answer1", null);
		yield return lineBreak();
		yield return link(@"Press ""I am a prisoner within these walls""", @"answer1", null);
		yield return lineBreak();
		yield return link(@"Press ""I am nobody""", @"answer1", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #13: home

	void passage13_Init()
	{
		this.Passages[@"home"] = new StoryPassage(@"home", new string[]{  }, passage13_Main);
	}

	IStoryThread passage13_Main()
	{
		yield return text(@"You hurry back to the edge of the maze, to your son Icarus. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"--");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"Young Icarus looks up as you approach, his eyes large and clear. He's long since learned to avoid making even the smallest of sounds. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"You gather together what you can of your materials and tools holding the wooden frames you've made aloft. Your inventor's hands work over the frames, applying each feather with care and sealing each in place with a drop of wax. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"Soon the ");
		yield return link(@"wings are complete...", @"wings are complete...", null);
		yield return text(@".");
		yield return lineBreak();
		yield break;
	}


	// .............
	// #14: wings are complete...

	void passage14_Init()
	{
		this.Passages[@"wings are complete..."] = new StoryPassage(@"wings are complete...", new string[]{  }, passage14_Main);
	}

	IStoryThread passage14_Main()
	{
		yield return text(@"...but of course there's only enough material to make one set of wings. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"For only one of you to leave this place. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"Of course you knew that all along... ", @" choice", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"And yet you've scarcely wanted to believe... ", @" choice", null);
		yield return lineBreak();
		yield return lineBreak();
		yield break;
	}


	// .............
	// #15:  choice

	void passage15_Init()
	{
		this.Passages[@" choice"] = new StoryPassage(@" choice", new string[]{  }, passage15_Main);
	}

	IStoryThread passage15_Main()
	{
		yield return text(@"And yet here you stand, with one last choice to make. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"Take the wings and fly away.", @"Take the wings and fly away.", null);
		yield return lineBreak();
		yield return link(@"Give the wings to Icarus and let him fly away.", @"Give the wings to Icarus and let him fly away.", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #16: Take the wings and fly away.

	void passage16_Init()
	{
		this.Passages[@"Take the wings and fly away."] = new StoryPassage(@"Take the wings and fly away.", new string[]{  }, passage16_Main);
	}

	IStoryThread passage16_Main()
	{
		yield return text(@"Icarus watches as you strap the wings to your arms. He is still. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"""I have to go now, Icarus,"" you say. ""Icarus--"" ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"""Stay safe."" ", @" final2", null);
		yield return lineBreak();
		yield return link(@"""I'm sorry."" ", @" final2", null);
		yield return lineBreak();
		yield return link(@"""I had no choice."" ", @" final2", null);
		yield return lineBreak();
		yield return lineBreak();
		yield break;
	}


	// .............
	// #17: Give the wings to Icarus and let him fly away.

	void passage17_Init()
	{
		this.Passages[@"Give the wings to Icarus and let him fly away."] = new StoryPassage(@"Give the wings to Icarus and let him fly away.", new string[]{  }, passage17_Main);
	}

	IStoryThread passage17_Main()
	{
		yield return text(@"You strap the wings to Icarus, help to tighten the harness to fit his small body. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"""Stay low, and stay quiet,"" you tell him. ""And..."" ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"""Farewell."" ", @" final1", null);
		yield return lineBreak();
		yield return link(@"""Remember me."" ", @" final1", null);
		yield return lineBreak();
		yield return link(@"""Be free."" ", @" final1", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #18:  final1

	void passage18_Init()
	{
		this.Passages[@" final1"] = new StoryPassage(@" final1", new string[]{  }, passage18_Main);
	}

	IStoryThread passage18_Main()
	{
		yield return text(@"He jumps. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"For a second he falls, but then the next second his large wings catch the sea breeze and bear him aloft, over the Aegean. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"His small body is haloed in the light of the sun. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"THE END", @"THE END", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #19: THE END

	void passage19_Init()
	{
		this.Passages[@"THE END"] = new StoryPassage(@"THE END", new string[]{  }, passage19_Main);
	}

	IStoryThread passage19_Main()
	{
		yield return text(@"DAEDALUS");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"Created by Devi Acharya for the 2018 Twine Games Jam.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"Made with Twine and Unity using Cradle. SFX courtesy of freesound.org. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"--");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"RESTART", @"RESTART", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #20: Twine

	void passage20_Init()
	{
		this.Passages[@"Twine"] = new StoryPassage(@"Twine", new string[]{  }, passage20_Main);
	}

	IStoryThread passage20_Main()
	{
		yield return text(@"Double-click this passage to edit it.");
		yield return lineBreak();
		yield break;
	}


	// .............
	// #21: Unity

	void passage21_Init()
	{
		this.Passages[@"Unity"] = new StoryPassage(@"Unity", new string[]{  }, passage21_Main);
	}

	IStoryThread passage21_Main()
	{
		yield return text(@"Double-click this passage to edit it.");
		yield return lineBreak();
		yield break;
	}


	// .............
	// #22: RESTART

	void passage22_Init()
	{
		this.Passages[@"RESTART"] = new StoryPassage(@"RESTART", new string[]{  }, passage22_Main);
	}

	IStoryThread passage22_Main()
	{
		yield return text(@"Double-click this passage to edit it.");
		yield return lineBreak();
		yield break;
	}


	// .............
	// #23:  final2

	void passage23_Init()
	{
		this.Passages[@" final2"] = new StoryPassage(@" final2", new string[]{  }, passage23_Main);
	}

	IStoryThread passage23_Main()
	{
		yield return text(@"You brace yourself at the end of the cliff and jump, spreading your wings wide--");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"You are caught by the Aegean winds, soaring, the lightness filling your soul in a way only true freedom can. Already the maze is far behind you, receding from view and from your thoughts.");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"You let the light of the sun wash over you, revelling in its warmth. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"THE END", @"THE END", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #24: answer1

	void passage24_Init()
	{
		this.Passages[@"answer1"] = new StoryPassage(@"answer1", new string[]{  }, passage24_Main);
	}

	IStoryThread passage24_Main()
	{
		yield return text(@"As you press the button, the box's lid falls away. Inside the box you see a feather. You tuck the feather into your pouch. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"Onwards", @"Onwards", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #25: answer2

	void passage25_Init()
	{
		this.Passages[@"answer2"] = new StoryPassage(@"answer2", new string[]{  }, passage25_Main);
	}

	IStoryThread passage25_Main()
	{
		yield return text(@"As you press the button, the box's lid falls away. Inside the box you see a feather. You tuck the feather into your pouch. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"You have everything you need. Time to go ");
		yield return link(@"home", @"home", null);
		yield return text(@". ");
		yield return lineBreak();
		yield break;
	}


}