/*
------------------------------------------------
Generated by Cradle 2.0.1.0
https://github.com/daterre/Cradle

Original file: Daedalus1.html
Story format: Sugar
------------------------------------------------
*/

using System.Collections;
using System.Collections.Generic;
using UnityEngine;
using Cradle;
using IStoryThread = System.Collections.Generic.IEnumerable<Cradle.StoryOutput>;
using Cradle.StoryFormats.Sugar;

public partial class @Daedalus1: Cradle.StoryFormats.Sugar.SugarStory
{
	#region Variables
	// ---------------

	public class VarDefs: RuntimeVars
	{
		public VarDefs()
		{
		}

	}

	public new VarDefs Vars
	{
		get { return (VarDefs) base.Vars; }
	}

	// ---------------
	#endregion

	#region Initialization
	// ---------------


	@Daedalus1()
	{
		this.StartPassage = "Home";

		base.Vars = new VarDefs() { Story = this, StrictMode = false };


		base.Init();
		passage1_Init();
		passage2_Init();
		passage3_Init();
		passage4_Init();
		passage5_Init();
		passage6_Init();
		passage7_Init();
		passage8_Init();
		passage9_Init();
		passage10_Init();
		passage11_Init();
		passage12_Init();
		passage13_Init();
	}

	// ---------------
	#endregion

	// .............
	// #1: Home

	void passage1_Init()
	{
		this.Passages[@"Home"] = new StoryPassage(@"Home", new string[]{  }, passage1_Main);
	}

	IStoryThread passage1_Main()
	{
		yield return text(@"''Home''");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"This corner of the labyrinth is the safest place you could find to keep your son sheltered. Over the years you have built up detritus, trinkets and half-made inventions from what you could scavenge within the maze.  ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"But you have finally thought of a way out--a way to be rid of this place forever. You just need to take one last journey into the maze, collecting feathers for what will be your last invention. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"This is the only part of the maze that opens up to the outside world. A sheer cliff face drops off and below, you can hear the ocean waves crash against unforgiving stone. Birds freewheel through the sea breeze, mocking you in their freedom. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"Onwards", @"Onwards", null);
		yield return lineBreak();
		yield return lineBreak();
		yield break;
	}


	// .............
	// #2: Onwards

	void passage2_Init()
	{
		this.Passages[@"Onwards"] = new StoryPassage(@"Onwards", new string[]{  }, passage2_Main);
	}

	IStoryThread passage2_Main()
	{
		yield return text(@"Double-click this passage to edit it.");
		yield return lineBreak();
		yield break;
	}


	// .............
	// #3: Feather 1

	void passage3_Init()
	{
		this.Passages[@"Feather 1"] = new StoryPassage(@"Feather 1", new string[]{  }, passage3_Main);
	}

	IStoryThread passage3_Main()
	{
		yield return text(@"//This is like no ordinary maze. There is no way in and there is no way out. Those consigned to walk its walls will do so for all of eternity.//");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"You find a feather here, nestled in the crack between two stones.");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"Onwards", @"Onwards", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield break;
	}


	// .............
	// #4: Feather 2

	void passage4_Init()
	{
		this.Passages[@"Feather 2"] = new StoryPassage(@"Feather 2", new string[]{  }, passage4_Main);
	}

	IStoryThread passage4_Main()
	{
		yield return text(@"//You try to think of what Icarus must be going through, living every moment of his life with only fear and silence. What little does he remember of the outside world?//");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"A feather, damp but usable, clings to one of the loose stones here. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"Onwards", @"Onwards", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #5: Feather 3

	void passage5_Init()
	{
		this.Passages[@"Feather 3"] = new StoryPassage(@"Feather 3", new string[]{  }, passage5_Main);
	}

	IStoryThread passage5_Main()
	{
		yield return text(@"//How did you end up in this place? You try to trace back the chain of events, but every thread seems tangled, every piece disjointed. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"The real madness, you think, was building this maze in the first place. //");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"A feather drifts down from above your head. You snatch it from the air. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"Onwards", @"Onwards", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #6: Feather 4

	void passage6_Init()
	{
		this.Passages[@"Feather 4"] = new StoryPassage(@"Feather 4", new string[]{  }, passage6_Main);
	}

	IStoryThread passage6_Main()
	{
		yield return text(@"//Has it been months? Years? You have had little to reference but the length of your hair and the hollow of your stomach. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"Little Icarus had tried to keep track at first. But as days drifted into weeks, he began to slump under the futility of such a task.//");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"A feather, pristine, lay on the floor before you. You carefully tuck it away. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"Onwards", @"Onwards", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #7: Feather 5

	void passage7_Init()
	{
		this.Passages[@"Feather 5"] = new StoryPassage(@"Feather 5", new string[]{  }, passage7_Main);
	}

	IStoryThread passage7_Main()
	{
		yield return text(@"//You feel the halting of your breath, the way each gasp catches in your throat. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"A thought tries to work its way to conscious in your mind, something you try to bury back inside of you. The fear that even escaping from this maze will not mean freedom. The longing for that other means of release.//");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"A feather sits here in the grime. You take it and hurry on. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"Onwards", @"Onwards", null);
		yield return lineBreak();
		yield return lineBreak();
		yield return lineBreak();
		yield break;
	}


	// .............
	// #8: Feather 6

	void passage8_Init()
	{
		this.Passages[@"Feather 6"] = new StoryPassage(@"Feather 6", new string[]{  }, passage8_Main);
	}

	IStoryThread passage8_Main()
	{
		yield return text(@"//You used to think yourself a genius, that your mind could provide you with whatever you desired. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"Now, your desires are few. A warm bed. The ability to laugh with your child.//");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"You find a feather here, in the cracks between two stones. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"Onwards", @"Onwards", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #9: Feather 10

	void passage9_Init()
	{
		this.Passages[@"Feather 10"] = new StoryPassage(@"Feather 10", new string[]{  }, passage9_Main);
	}

	IStoryThread passage9_Main()
	{
		yield return text(@"A small stone box, unadorned, sits here, a question engraved into its top. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"Three buttons decorate its sides. You reason that pressing one of the buttons will open the box. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"The lid reads, ''Why do you want freedom?''");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"Press ""I want to live without every moment marked by fear"" ", @"| answer1", null);
		yield return lineBreak();
		yield return link(@"Press ""I want revenge for what has been done to me"" ", @"| answer1", null);
		yield return lineBreak();
		yield return link(@"Press ""I want my son to know the world beyond these walls"" ", @"| answer1", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #10: Feather 9

	void passage10_Init()
	{
		this.Passages[@"Feather 9"] = new StoryPassage(@"Feather 9", new string[]{  }, passage10_Main);
	}

	IStoryThread passage10_Main()
	{
		yield return text(@"A small stone box sits here, shining under the light of your lantern. You can see that its lid is marked with a question. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"Three buttons decorate its sides. You reason that pressing one of the buttons will open the box. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"The lid reads, ''What keeps you here?''");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"Press ""My own inability keeps me here. If only I could think of a means of escape..."" ", @"| answer1", null);
		yield return lineBreak();
		yield return link(@"Press ""A tyrant-king keeps me here, to be locked away forever"" ", @"| answer1", null);
		yield return lineBreak();
		yield return link(@"Press ""You keep me here by denying me what I need"" ", @"| answer1", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #11: Feather 8

	void passage11_Init()
	{
		this.Passages[@"Feather 8"] = new StoryPassage(@"Feather 8", new string[]{  }, passage11_Main);
	}

	IStoryThread passage11_Main()
	{
		yield return text(@"A small stone box, its corners crumbling, sits here. A question is engraved into its lid. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"Three buttons decorate its sides. You reason that pressing one of the buttons will open the box. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"The lid reads, ''Why are you here?''");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"Press ""I was trapped here by my own hubris"" ", @"| answer1", null);
		yield return lineBreak();
		yield return link(@"Press ""I was imprisoned here by a cruel tyrant"" ", @"| answer1", null);
		yield return lineBreak();
		yield return link(@"Press ""I am not here. Walls cannot hold my mind"" ", @"| answer1", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #12: Feather 7

	void passage12_Init()
	{
		this.Passages[@"Feather 7"] = new StoryPassage(@"Feather 7", new string[]{  }, passage12_Main);
	}

	IStoryThread passage12_Main()
	{
		yield return text(@"A small stone box covered with lichen sits here, a question engraved into its top. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"Three buttons decorate its sides. You reason that pressing one of the buttons will open the box. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return text(@"The lid reads, ''Who are you?''");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"Press ""I am Daedalus, inventor and father"" ", @"| answer1", null);
		yield return lineBreak();
		yield return link(@"Press ""I am a prisoner within these walls"" ", @"| answer1", null);
		yield return lineBreak();
		yield return link(@"Press ""I am nobody"" ", @"| answer1", null);
		yield return lineBreak();
		yield break;
	}


	// .............
	// #13:  answer1

	void passage13_Init()
	{
		this.Passages[@" answer1"] = new StoryPassage(@" answer1", new string[]{  }, passage13_Main);
	}

	IStoryThread passage13_Main()
	{
		yield return text(@"As you press the button, the box's lid falls away. Inside the box you see a feather. You tuck the feather into your pouch. ");
		yield return lineBreak();
		yield return lineBreak();
		yield return link(@"Onwards", @"Onwards", null);
		yield return lineBreak();
		yield break;
	}


}